# Generated by Django 2.2.10 on 2021-01-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210111_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text_answer', 'text answer'), ('choose_single_answer', 'choose single answer'), ('choose_multiple_answer', 'choose multiple answer')], max_length=256),
        ),
    ]
