# Generated by Django 2.2.10 on 2021-01-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210111_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text_answer', 'text answer'), ('choose_answer', 'choose answer')], max_length=256),
        ),
    ]
