# Generated by Django 2.2.10 on 2021-01-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210111_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChooseAnswer',
            new_name='ChooseAnswerBody',
        ),
    ]
