# Generated by Django 2.2.10 on 2021-01-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210111_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='poll_id',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text_answer', 'text answer'), ('choose_single_answer', 'choose single answer'), ('choose_multiple_answer', 'choose multiple answer')], max_length=256),
        ),
        migrations.DeleteModel(
            name='ChooseAnswerBody',
        ),
    ]
