# Generated by Django 2.2.10 on 2021-01-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210112_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll_id',
            new_name='poll',
        ),
    ]
